version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    # Use env_file to load all variables from .env, including the updated OLLAMA_BASE_URL
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=manage.py
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - flask-app
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080" # Changed host port to 8081 to avoid conflict
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
