"""Add Category model and relationship with Audiobook

Revision ID: 041480c9a078
Revises: 71bdde51861e
Create Date: 2025-04-24 02:14:51.204989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041480c9a078'
down_revision = '71bdde51861e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('audiobook_categories',
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('audiobook_id', 'category_id')
    )
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=524), autoincrement=False, nullable=True))

    op.drop_table('audiobook_categories')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    # ### end Alembic commands ###
