"""Add user_books table for MP3 downloads

Revision ID: 37fecb09bb90
Revises: f9292c9d74cf
Create Date: 2025-11-17 01:54:36.379945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fecb09bb90'
down_revision = 'f9292c9d74cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mp3_file_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'audiobook_id', name='unique_user_audiobook')
    )
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_books_audiobook_id'), ['audiobook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_books_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_books_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_books_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_books_status'))
        batch_op.drop_index(batch_op.f('ix_user_books_audiobook_id'))

    op.drop_table('user_books')
    # ### end Alembic commands ###
