"""Refactor Audiobook model fields

Revision ID: 40b7b4c1b218
Revises: 
Create Date: 2025-04-24 01:52:43.277919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b7b4c1b218'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=524), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=524), nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('book_thumbnail')
        batch_op.drop_column('yt_description')
        batch_op.drop_column('book_description')
        batch_op.drop_column('yt_title')
        batch_op.drop_column('book_data_url')
        batch_op.drop_column('published')
        batch_op.drop_column('book_isbn')
        batch_op.drop_column('yt_thumbnail')
        batch_op.drop_column('book_subtitle')
        batch_op.drop_column('page_count')
        batch_op.drop_column('book_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('book_subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('yt_thumbnail', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('book_isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('book_data_url', sa.VARCHAR(length=524), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('yt_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('book_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('yt_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('book_thumbnail', sa.VARCHAR(length=524), autoincrement=False, nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('tags')
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
