"""sync up db

Revision ID: 71bdde51861e
Revises: 40b7b4c1b218
Create Date: 2025-04-24 02:02:59.861881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bdde51861e'
down_revision = '40b7b4c1b218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
