"""Add YoutubeSearchState model

Revision ID: 8b218bbb7d32
Revises: c7805e95beae
Create Date: 2025-04-25 23:57:27.928926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b218bbb7d32'
down_revision = 'c7805e95beae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_search_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('youtube_search_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_search_state_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_search_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_search_state_key'))

    op.drop_table('youtube_search_state')
    # ### end Alembic commands ###
