"""Add SkippedVideo model

Revision ID: a50d141a7448
Revises: 041480c9a078
Create Date: 2025-04-25 01:43:00.002608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50d141a7448'
down_revision = '041480c9a078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skipped_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=24), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skipped_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skipped_videos_video_id'), ['video_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skipped_videos_video_id'))

    op.drop_table('skipped_videos')
    # ### end Alembic commands ###
