"""sync up model to db

Revision ID: c7805e95beae
Revises: f148a59bf5b4
Create Date: 2025-04-25 01:49:54.372117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7805e95beae'
down_revision = 'f148a59bf5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped_videos', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
