"""Add reason column to SkippedVideo

Revision ID: f148a59bf5b4
Revises: a50d141a7448
Create Date: 2025-04-25 01:47:00.437574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f148a59bf5b4'
down_revision = 'a50d141a7448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped_videos', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
