"""Add rating column to audiobooks table

Revision ID: f9292c9d74cf
Revises: 1f2731e232a1
Create Date: 2025-11-16 23:43:45.461913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9292c9d74cf'
down_revision = '1f2731e232a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobooks', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
